[net]
git-fetch-with-cli = true

[source.mirror]
registry = "file:////home/loancold/Projects/test_rust/docker_rust/Cargo-Ecosystem-Monitor/crates.io-index"

[source.crates-io]
replace-with = "mirror"
