[package]
name = "ruf_audit_virtual"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-lock = { version = "10.0.0", features = ["dependency-tree"] }

fxhash = "0.2.1"
petgraph = "0.6.5"
postgres = "0.19.9"
semver = "1.0.23"
