[package]
name = "cargo_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.7.2"
cargo = "0.68.0"
anyhow = "1.0.69"
walkdir = "2.3.2"
lazy_static = "1.4.0"
regex = "1.7.1"
